---
- gather_facts: off
  hosts: cisco6
  tasks: 
    - ios_banner:
        banner: login
        text: |
          *** TEST ***
          test test test
          *** TEST ***
        state: present
      notify: write mem

  handlers:
    - name: write mem
      ios_command:
        commands: write mem
      changed_when: True


